# Token OpenBao - Tom
SetEnv VAULT_TOKEN "s.IeMUBW8kOFRikMXChv2W5TkQ"
SetEnv VAULT_ADDR "http://127.0.0.1:8201"
SetEnv DB_PASSWORD "nexivaultomDba"

<Directory /var/www/html/nexivaultom>
    AllowOverride None
    Require all granted
</Directory>
